version: '3.9'

services:
  web:
    build: .
    command: gunicorn dyno_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: newmozilla_db
      POSTGRES_USER: newmozilla_user
      POSTGRES_PASSWORD: newmobzilla

volumes:
  postgres_data:
