# Generated by Django 5.2.3 on 2025-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_glb', models.FileField(upload_to='original/')),
                ('optimized_glb', models.FileField(blank=True, upload_to='optimized/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
