# Generated by Django 5.2.3 on 2025-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glbmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scene',
            name='optimized_glb',
            field=models.FileField(blank=True, upload_to='optimized_3dmodels/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='original_glb',
            field=models.FileField(upload_to='original_3dmodels/'),
        ),
    ]
