# Generated by Django 5.2.3 on 2025-09-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_comment_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
