# Generated by Django 5.2.3 on 2025-09-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='device',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('iphone', 'Iphone')], max_length=25),
        ),
    ]
